security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider:   fos_userbundle
                login_path: /login
                check_path: /login_check
#                use_referer: true
            logout:       true
            anonymous:    true
        
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
    
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    